############# English navigation ##############

# main menu
[[main]]
name = "Главная"
url = ""
weight = 1

[[main]]
name = "О нас"
url = "about/"
weight = 2

[[main]]
name = "Виды работ"
url = "project/"
weight = 3

[[main]]
name = "Статьи"
url = "blog/"
weight = 4

[[main]]
weight = 5
name = "Ещё"
hasChildren = true

  [[main]]
  parent = "Ещё"
  name = "Гарантия"
  url = "service/"
  weight = 1

  [[main]]
  parent = "Ещё"
  name = "Цены"
  url = "pricing/"
  weight = 2

  [[main]]
  parent = "Ещё"
  name = "FAQ"
  url = "faq/"
  weight = 3
  
[[main]]
name = "Контакты"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "О нас"
url = "about/"
weight = 2

[[footer]]
name = "Виды работ"
url = "project/"
weight = 3

[[footer]]
name = "Гарантия"
url = "service/"
weight = 4

[[footer]]
name = "Цены"
url = "pricing/"
weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Контакты"
url = "contact/"
weight = 7